org: groupcounseling
app: groupcounseling-app
service: GroupCounseling-app

plugins:
  - serverless-offline
  - serverless-dynamodb-local
custom:
  stage: dev
  serverless-offline:
    httpPort: 5000
    stageVariables:
      foo: "bar"
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "execute-api:ManageConnections"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resources: "*"

functions:
  - ${file(./resource-functions/user.yml)}
  - ${file(./resource-functions/debug.yml)}
  - ${file(./resource-functions/communicate.yml)}
  - ${file(./resource-functions/analysis.yml)}
  - ${file(./resource-functions/websock.yml)}

resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionIds
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
